on: pull_request

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2
        
    - uses: saadmk11/changelog-ci@v0.8.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
